apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: tyk-cicd-demo-{{ include "noderize.fullname" . }}
  namespace: apps
spec:
  name: {{ include "noderize.fullname" . }}
  use_keyless: true
  protocol: https
  active: true
  domain: {{ .Values.api.domain }}
  proxy:
    target_url: http://{{ include "noderize.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}/api
    listen_path: {{ .Values.api.listenPath }}
    strip_listen_path: true
  response_processors:
    - name: header_injector
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        use_extended_paths: true
        global_headers:
          authorization: Bearer foobar
